TempUpload
see-the-glory/on-you-frontend pull request #22
Opened 2022-07-15 07:48 UTC by gyu-bin

아직 다 적용한건 아니고 몇개 파일이 빠졌습니다. 
백업이 덜 되었더라구요.
복원후 추가적용 하겠습니다.

2022-07-19 01:36 UTC, jglee-Cm7 requested changes

2022-07-19 01:36 UTC, jglee-Cm7 commented on navigation/ClubCreationStack.tsx
> -
내가 만든거 다 지워버릴려고 하면 어떡하니
이 페이지는 commit 목록에서 지워주세요.

2022-07-19 01:36 UTC, jglee-Cm7 commented on navigation/ClubCreationStack.tsx
> -import ClubCreationSuccess from "../screens/ClubCreation/ClubCreationSuccess";
이 페이지는 commit 목록에서 지워주세요.

2022-07-19 01:36 UTC, jglee-Cm7 commented on navigation/LoginStack.tsx
> +    <NativeStack.Navigator screenOptions={{ headerShown: false }}>
tab 간격 다른거는 git add 하고 commit 하기 전에 보고 제외합시다.
vscode 쓰면 prettier 환경 맞추자

2022-07-19 01:36 UTC, jglee-Cm7 commented on navigation/Root.tsx
> -import ClubStack from "./ClubStack";
아무래도 git fetch / pull 안하고 머지한거같은데,
기존 소스 변형하지말고, 수정한것만 적용합시다

2022-07-21 06:02 UTC, closed without merging

2022-07-21 06:02 UTC, gyu-bin commented
xx